### ISSUE TITLE
Unable to import index.css

### ISSUE THREAD

**Issue by dudduss** [npapapietro/nutritionfactstable#2]
Hi, getting this error when I try to render this component:

`Unable to resolve "./index.css" from "node_modules/nutritionfactstable/dist/index.js"`

I am currently working on a Typescript Project with React Native via Expo. It seems like it should work seamlessly, but I'm not able to get past this.

**Comment by npapapietro** [comment]
Thanks for alerting me to this, I'm looking into it now.

**Comment by npapapietro** [comment]
@dudduss I pushed a new version to npm. It should take care of that. I had missed building sass -> css. Let me know if that fixes it for you.

**Comment by dudduss** [comment]
Unfortunately looks like that didn't change anything. Still seeing this error when I try to run my expo emulator:

```
Failed building JavaScript bundle.
Unable to resolve "./index.css" from "node_modules/nutritionfactstable/dist/index.js"
```

Here's a more descriptive image:

![image](https://user-images.githubusercontent.com/9653576/105642971-e69f0b00-5e41-11eb-8995-e0a06bdff9af.png)

Here's how my `package.json` looks - lemme know if this is correct:

```
"nutritionfactstable": "^1.1.9",
```

**Comment by npapapietro** [comment]
So I was able to start a brand new project using expo. Since I am not on a Mac I have minimal ability to debug the `yarn ios` command and I don't have the Android developer tools setup, but I can confirm the `yarn web` works. Could you confirm it works for that command? I'm suspecting it something with how the library is bundled.

Are you able to look inside the `node_modules` folder and confirm there is indeed `index.css` in there as well as `index.js`?

**Comment by dudduss** [comment]
I'm actually using `npm` to install the module and it seems to work fine except when I actually try to run my emulator -- do you know if `npm` should still work?

this is what my file hierarchy looks like:

![image](https://user-images.githubusercontent.com/9653576/105810820-7aff8f80-5f60-11eb-88a4-03d4ee3c5ce4.png)

**Comment by npapapietro** [comment]
I am not sure, but there was some similar issues here https://github.com/expo/expo/issues/6722

I have pushed a new version that renames index.css => main.css to see if it has an issue with the name `index`. Unfortunately it seems to be an issue with expo.

I'll keep this open until you can resolve it with expo

**Comment by nerdferby** [comment]
I'm also having this issue and can't find a workaround. Here is my `package.json` https://pastebin.com/GMyULD8N

**Comment by npapapietro** [comment]
I've bumped the version with a migration to stylized components over SCSS. Hopefully this fixes it otherwise open another ticket.
